name: Android CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Webkit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug
      run: ./gradlew assembleSystemDebug
    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
      id: sign_app_wd
      with:
        releaseDirectory: ./app/build/outputs/apk/system/debug
        signingKeyBase64: ${{ secrets.DEBUG_SIGNING_KEY }}
        alias: ${{ secrets.DEBUG_ALIAS }}
        keyStorePassword: ${{ secrets.DEBUG_KEY_PASSWORD }}
        keyPassword: ${{ secrets.DEBUG_KEY_PASSWORD }}   
    - uses: actions/upload-artifact@v2
      with:
        name: WebView debug
        path: ${{steps.sign_app_wd.outputs.signedReleaseFile}}
        
    - name: Build Release
      run: ./gradlew assembleSystemRelease
    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
      id: sign_app_wr
      with:
        releaseDirectory: ./app/build/outputs/apk/system/release
        signingKeyBase64: ${{ secrets.DEBUG_SIGNING_KEY }}
        alias: ${{ secrets.DEBUG_ALIAS }}
        keyStorePassword: ${{ secrets.DEBUG_KEY_PASSWORD }}
        keyPassword: ${{ secrets.DEBUG_KEY_PASSWORD }}   
    - uses: actions/upload-artifact@v2
      with:
        name: WebView release
        path: ${{steps.sign_app_wr.outputs.signedReleaseFile}}

    - name: Multicheck
      run: ./gradlew clean assembleSystem assembleAndroidTest lint checkstyle ktlint pmd detekt test

  Gecko:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug
      run: ./gradlew assembleGeckoDebug
    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
      id: sign_app_gd
      with:
        releaseDirectory: ./app/build/outputs/apk/gecko/debug
        signingKeyBase64: ${{ secrets.DEBUG_SIGNING_KEY }}
        alias: ${{ secrets.DEBUG_ALIAS }}
        keyStorePassword: ${{ secrets.DEBUG_KEY_PASSWORD }}
        keyPassword: ${{ secrets.DEBUG_KEY_PASSWORD }}   
    - uses: actions/upload-artifact@v2
      with:
        name: Gecko debug
        path: ${{steps.sign_app_gd.outputs.signedReleaseFile}}
      
    - name: Build Release
      run: ./gradlew assembleGeckoRelease
    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
      id: sign_app_gr
      with:
        releaseDirectory: ./app/build/outputs/apk/gecko/release
        signingKeyBase64: ${{ secrets.DEBUG_SIGNING_KEY }}
        alias: ${{ secrets.DEBUG_ALIAS }}
        keyStorePassword: ${{ secrets.DEBUG_KEY_PASSWORD }}
        keyPassword: ${{ secrets.DEBUG_KEY_PASSWORD }}   
    - uses: actions/upload-artifact@v2
      with:
        name: Gecko release
        path: ${{steps.sign_app_gr.outputs.signedReleaseFile}}

    - name: Multicheck
      run: ./gradlew clean assembleGecko assembleAndroidTest lint checkstyle ktlint pmd detekt test